server:
  port: 8082

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ekholabs/elsie-dee-configs.git

management:
  security:
    enabled: false

endpoints:
  refresh:
    enabled: true
  restart:
    enabled: true
