server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/development/git/microservices-config
endpoints:
  refresh:
    enabled: true
  restart:
    enabled: true
    pause-endpoint:
      enabled: true
    resume-endpoint:
      enabled: true
  shutdown:
    enabled: true